### ISSUE TITLE
1.18.2 exception ticking world crash

### ISSUE THREAD

**Issue by soggyfever4568** [Etyl/ImmersiveFarming#1]
when ever i plant beetroot my game crashes and I suspect it may be your causing it cause i disabled it and it no longer crashes here's the log: https://pastebin.com/Qf87eBZe

**Comment by etyl** [comment]
Hi, sorry about this bug.
I made a quick patch that should fix the issue, let me know if it works!
https://github.com/Etyl/ImmersiveFarming/releases/tag/1.18.2-0.2.2

**Comment by soggyfever4568** [comment]
sorry for the late response, yup that works fine now, though one other issue i want to bring up is that cocoa beans, cactus and sugar cane no longer grow at all. ( yes i have simply seasons set correctly)

**Comment by etyl** [comment]
Should be fixed now :)
https://github.com/Etyl/ImmersiveFarming/releases/tag/1.18.2-0.2.3
