### ISSUE TITLE
sprinklers

### ISSUE THREAD

**Issue by zucckled** [Etyl/ImmersiveFarming#2]
okay i think its something i am doing wrong but im not sure. i cannot get the sprinklers to work. ive tried so many things and have read the manual multiple times but im just confused on what to do

**Comment by etyl** [comment]
Sprinklers work like pumps, you right click with a hammer on the sides of the bottom block to configure the inputs/outputs of the sprinkler. Then you can connect your sprinkler with pipes to your network. Add screenshots if you still can't make it work.
